on:
  schedule:
  - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'Manual testing'
      tags:
        description: 'Test scenario tags'

jobs:
  sp_alert:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      R_TELEGRAM_BOT_SPALERT_BOT: ${{ secrets.R_TELEGRAM_BOT_SPALERT_BOT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: |
          install.packages(c("telegram","dplyr","readr","stringr","glue","purrr", "httr2"))
        shell: Rscript {0}

      - name: Telegram
        run: Rscript telegram.R
