name: sp_alert

on:
  schedule:
     - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sp_alert
  cancel-in-progress: true

jobs:
  sp_alert:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      R_TELEGRAM_BOT_SPALERT_BOT: ${{ secrets.R_TELEGRAM_BOT_SPALERT_BOT }}
      SPECIESLINK_API_KEY: ${{ secrets.SPECIESLINK_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies (with cache)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            telegram
            dplyr
            readr
            stringr
            glue
            purrr
            httr2
          needs: false

      - name: Run script
        run: Rscript telegram.R

      - name: Commit results
        run: |
          if [[ -n "$(git status --porcelain dados/characidium_database.csv)" ]]; then
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add dados/characidium_database.csv
            git commit -m "Update data"
            git push
          fi
